source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'SwiftHelpers_Tests' do
  pod 'SwiftHelpers', :path => '../'
  pod 'Nimble', :git => 'https://github.com/bartekchlebek/Nimble.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
